package dev.wyck.worldgen.noise;

import com.google.common.base.Preconditions;
import dev.wyck.annotations.AsOf;
import dev.wyck.factory.ConstructWireProvider;
import dev.wyck.wrapper.Wrapper;
import dev.wyck.wrapper.decode.Decoder;
import org.jspecify.annotations.NullMarked;

/**
 * The vertical bounds used by a noise-based chunk generator.
 *
 * @since 2.4.0
 * @version 4.0.0
 * @author Jsinco
 */
@NullMarked
@AsOf("2.4.0")
public interface NoiseSettings extends Wrapper {

    /** The default noise bounds used by the Overworld. */
    @AsOf("2.4.0")
    NoiseSettings OVERWORLD = of(-64, 384);

    /** The default noise bounds used by the Nether. */
    @AsOf("2.4.0")
    NoiseSettings NETHER = of(0, 128);

    /** The default noise bounds used by the End. */
    @AsOf("2.4.0")
    NoiseSettings END = of(0, 128);

    /** The default noise bounds used by the caves preset. */
    @AsOf("2.4.0")
    NoiseSettings CAVES = of(-64, 192);

    /** The default noise bounds used by the floating-islands preset. */
    @AsOf("2.4.0")
    NoiseSettings FLOATING_ISLANDS = of(0, 256);

    /**
     * The minimum y-coordinate generated by the noise generator.
     * @return the minimum generation y-coordinate
     * @since 2.4.0
     */
    @AsOf("2.4.0")
    int minY();

    /**
     * The total vertical height generated by the noise generator.
     * @return the generation height
     * @since 2.4.0
     */
    @AsOf("2.4.0")
    int height();

    /**
     * Converts these noise settings back to a builder.
     * @return a builder containing these settings
     * @since 4.0.0
     */
    @AsOf("4.0.0")
    default Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Creates noise settings.
     * @param minY the minimum generation y-coordinate
     * @param height the total generation height, which must be a multiple of 16
     * @return new noise settings
     * @since 4.0.0
     */
    @AsOf("4.0.0")
    static NoiseSettings of(int minY, int height) {
        Preconditions.checkArgument(height % 16 == 0, "height must be a multiple of 16");
        Preconditions.checkArgument(minY + height <= 2032, "minY + height must be <= 2032");
        Preconditions.checkArgument(minY % 16 == 0, "minY must be a multiple of 16");
        record Holder() {
            static final ConstructWireProvider<NoiseSettings> WIRE = ConstructWireProvider.create(
                "dev.wyck.*?.worldgen.noise.NoiseSettingsImpl"
            );
        }
        return Holder.WIRE.construct(minY, height);
    }

    /**
     * Reads Minecraft noise settings.
     * @param minecraftSettings the Minecraft noise settings to read
     * @return the decoded noise settings
     * @since 3.3.0
     */
    @AsOf("3.3.0")
    static NoiseSettings decode(Object minecraftSettings) {
        record Holder() {
            static final Decoder<NoiseSettings> DECODER = Decoder.create(
                "dev.wyck.decode.worldgen.noise.NoiseSettingsDecoder"
            );
        }
        return Holder.DECODER.decode(minecraftSettings);
    }

    /**
     * Creates a new noise settings builder.
     * @return a new builder
     * @since 2.4.0
     */
    @AsOf("2.4.0")
    static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for {@link NoiseSettings}.
     *
     * @since 2.4.0
     * @version 4.0.0
     * @author Jsinco
     */
    @AsOf("2.4.0")
    final class Builder {
        private int minY = -64;
        private int height = 384;

        public Builder() {}

        /**
         * Creates a builder containing the values of existing noise settings.
         * @param settings the noise settings to copy
         * @since 4.0.0
         */
        @AsOf("4.0.0")
        public Builder(NoiseSettings settings) {
            this.minY = settings.minY();
            this.height = settings.height();
        }

        /**
         * Sets the minimum generation y-coordinate.
         * @param minY the minimum generation y-coordinate
         * @return this builder
         * @since 2.4.0
         */
        @AsOf("2.4.0")
        public Builder minY(int minY) {
            this.minY = minY;
            return this;
        }

        /**
         * Sets the total generation height.
         * @param height the generation height
         * @return this builder
         * @since 2.4.0
         */
        @AsOf("2.4.0")
        public Builder height(int height) {
            this.height = height;
            return this;
        }

        /**
         * Builds the noise settings.
         * @return the noise settings
         * @since 2.4.0
         */
        @AsOf("2.4.0")
        public NoiseSettings build() {
            return NoiseSettings.of(minY, height);
        }
    }
}
